### ISSUE TITLE
Authentication Problem with SamlTokenProvider.php Empty String

### ISSUE THREAD

**Issue by RezcommGuy** [vgrem/phpSPO#142]
Hi there,

Getting the issue below trying to use the phpSPO library, verified the user details and they are correct. Running from a local repo at the moment (`via PHP -S localhost:8000`). Messages in the PHP Error Log are the same.

```Warning: DOMDocument::loadXML(): Empty string supplied as input in /Users/user/repo/ana-sharepoint/phpSPO/src/Runtime/Auth/SamlTokenProvider.php on line 242

Warning: DOMXPath::query(): Undefined namespace prefix in /Users/user/repo/ana-sharepoint/phpSPO/src/Runtime/Auth/SamlTokenProvider.php on line 244

Warning: DOMXPath::query(): Invalid expression in /Users/user/repo/ana-sharepoint/phpSPO/src/Runtime/Auth/SamlTokenProvider.php on line 244

Notice: Trying to get property 'length' of non-object in /Users/user/repo/ana-sharepoint/phpSPO/src/Runtime/Auth/SamlTokenProvider.php on line 244

Warning: DOMXPath::query(): Undefined namespace prefix in /Users/user/repo/ana-sharepoint/phpSPO/src/Runtime/Auth/SamlTokenProvider.php on line 251

Warning: DOMXPath::query(): Invalid expression in /Users/user/repo/ana-sharepoint/phpSPO/src/Runtime/Auth/SamlTokenProvider.php on line 251

Notice: Trying to get property 'length' of non-object in /Users/user/repo/ana-sharepoint/phpSPO/src/Runtime/Auth/SamlTokenProvider.php on line 251
Authentication failed: Error trying to get a token, check your URL or credentials```

**Comment by RoelVB** [comment]
I got the same thing here.

This is the stack trace:
```
#0 C:\...\vendor\vgrem\php-spo\src\Runtime\Auth\SamlTokenProvider.php(159): Office365\PHP\Client\Runtime\Auth\SamlTokenProvider->processSecurityTokenResponse(NULL)#1 C:\...\vendor\vgrem\php-spo\src\Runtime\Auth\SamlTokenProvider.php(101): Office365\PHP\Client\Runtime\Auth\SamlTokenProvider->acquireSecurityToken('username', 'password)
#2 C:\...\vendor\vgrem\php-spo\src\Runtime\Auth\AuthenticationContext.php(69): Office365\PHP\Client\Runtime\Auth\SamlTokenProvider->acquireToken(Array)
#3 C:\...\fileupload.php(10): Office365\PHP\Client\R in C:\...\vendor\vgrem\php-spo\src\Runtime\Auth\SamlTokenProvider.php on line 256
```

**Comment by RoelVB** [comment]
It looks like Microsoft stopped supporting SAML 1.0, but a cannot find anything about this.
As far a I know there is no other SAML version that supports authentication with just a username and password.

**Comment by Eiglimar** [comment]
anyone solved this?

**Comment by briandgregory** [comment]
Also looking for a solution to this.

**Comment by evolvoltd** [comment]
If your password has special characters it can interfere with XML syntax, please try only alphanumeric password or escape your password.

**Comment by Carlosru** [comment]
I have the same problem when password is using special characters (some of them)  for example "%," but not always fail.

Case 1: When password starts with "%Ea" there is no problem everithing works ok...
Case 2:  When password have something like  "Abc%83421" , then the respond in adquiringToken fail in SamlTokenProvider.php

I have treid to escape "%" using &%percent;  and using &#25, and even escaping the numbers that follow the % but no luck, any idea how this can be solved?

Regards.

**Comment by valimero** [comment]
Any news on this ? Was it patched ?
