### ISSUE TITLE
I am receiving this error when i try to delete list item

### ISSUE THREAD

**Issue by yameenadnan** [vgrem/phpSPO#81]
Fatal error: Uncaught exception 'Exception' with message 'The type SP.ListItemEntityCollection does not support HTTP DELETE method.' in C:\xampp\htdocs\wordpress\wp-content\plugins\sharepoint\vendor\vgrem\php-spo\src\Runtime\OData\ODataClientRequest.php:110 Stack trace: #0 C:\xampp\htdocs\wordpress\wp-content\plugins\sharepoint\vendor\vgrem\php-spo\src\Runtime\OData\ODataClientRequest.php(61): Office365\PHP\Client\Runtime\OData\ODataClientRequest->validateResponse('{"error":{"code...') #1 C:\xampp\htdocs\wordpress\wp-content\plugins\sharepoint\vendor\vgrem\php-spo\src\Runtime\ClientRuntimeContext.php(134): Office365\PHP\Client\Runtime\OData\ODataClientRequest->executeQuery() #2 C:\xampp\htdocs\wordpress\wp-content\plugins\sharepoint\vendor\vgrem\php-spo\src\SharePoint\ClientContext.php(83): Office365\PHP\Client\Runtime\ClientRuntimeContext->executeQuery() #3 C:\xampp\htdocs\wordpress\wp-content\plugins\sharepoint\sharepoint.php(125): Office365\PHP\Client\SharePoint\ClientContext->executeQuery() #4 C:\xampp\htdocs\wordpres in C:\xampp\htdocs\wordpress\wp-content\plugins\sharepoint\vendor\vgrem\php-spo\src\Runtime\OData\ODataClientRequest.php on line 110

My line 125 contain this method $ctx->executeQuery();

Yameen Adnan

**Comment by cweiske** [comment]
@yameenadnan does this problem still occur with the latest phpSPO version?
